name: Mobile CI/CD

on:
  push:
    branches:
      - beta
      - main
    tags:
      - 'v*'

jobs:
  # -----------------------------
  # BETA BUILD (internal testing)
  # -----------------------------
  build_beta_android:
    if: github.ref == 'refs/heads/beta'
    name: Build Android (beta)
    type: build
    params:
      platform: android
      profile: beta

  build_beta_ios:
    if: github.ref == 'refs/heads/beta'
    name: Build iOS (beta)
    type: build
    params:
      platform: ios
      profile: beta

  # --------------------------------
  # PRODUCTION BUILD (on tag vX.X.X)
  # --------------------------------
  build_production_android:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Build Android (production)
    type: build
    params:
      platform: android
      profile: production

  build_production_ios:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Build iOS (production)
    type: build
    params:
      platform: ios
      profile: production

  # -----------------------------
  # SUBMIT TO STORES (production)
  # -----------------------------
  submit_android:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Submit Android
    type: submit
    needs: [build_production_android]
    params:
      build_id: ${{ needs.build_production_android.outputs.build_id }}

  submit_ios:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Submit iOS
    type: submit
    needs: [build_production_ios]
    params:
      build_id: ${{ needs.build_production_ios.outputs.build_id }}
